instruction: 
   input:
      path: ./src/main/resources/instruction/input/
      pattern: "*.ins"
   done: 
      path: ./src/main/resources/instruction/done/
   success: 
      path: ./src/main/resources/instruction/success/
   error: 
      path: ./src/main/resources/instruction/error/
   upload:
      path: ./src/main/resources/instruction/upload/